POST https://shopix.azurewebsites.net/feedback/addfeedback

Content-Type: application/json
{
    "name": "merna",
    "email": "merna215663@bue.edu.eg",
    "feedbackType":"bug",
    "comments": "good"
}
