PUT http://localhost:3000/products/65736aa57472144433aaac0f/updateproduct

Content-Type: application/json
{
    "name":"Microsoft Surface",
    "description":"A great laptop built and designed by Microsoft",
    "price":90000,
    "available":"no",
    "imgURL":"https://thumbs.dreamstime.com/b/apple-iphone-xs-silver-bright-colorful-background-front-back-sides-visible-concept-composition-ideal-commercial-143226402.jpg"
   
}